backend:
    #Engine configuration
    dboj_engine:
        host_db: localhost
        port_db: 5432
        user_db: postgres
        password_db: daniel
        user_xmpp: dboj_engine
        password_xmpp: engine

    #Comunication configuration
    dboj_comunication:
        host_xmpp: localhost
        user_xmpp: dboj_comunication
        password_xmpp: comunication