frontend:
    resource: "@FrontendBundle/Resources/config/routing.yml"
    prefix:   /

common:
    resource: "@CommonBundle/Resources/config/routing.yml"
    prefix:   /

competition:
    resource: "@CompetitionBundle/Resources/config/routing.yml"
    prefix:   /

problem:
    resource: "@ProblemBundle/Resources/config/routing.yml"
    
news:
    resource: "@NewsBundle/Resources/config/routing.yml"
    prefix:   /

backend:
    resource: "@BackendBundle/Resources/config/routing.yml"
    prefix:   /

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"
